name: Update stuff
on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  update_stuff:
    runs-on: ubuntu-20.04
    name: Update multiple dependencies
    steps:
      - uses: alwx/dependabot-batch-updater@main
        with:
          username: alwx
          repo-token: ${{ secrets.WORKFLOWSECRET }}
          repository: alwx/rasa
          directory: /
          package-manager: pip
          batch-size: 5
