name: Update stuff
on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  update_stuff:
    runs-on: ubuntu-20.04
    name: Automatically reorder issues by priority in "Backlog" column of "Production" and "Loop" projects
    steps:
      - uses: alwx/dependabot-batch-updater@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: alwx/rasa
          directory: /
          package-manager: pip
          batch-size: 3
