name: Update stuff
on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  update_dependencies:
    runs-on: ubuntu-20.04
    name: Update dependencies
    steps:
      - uses: RasaHQ/dependabot-batch-updater@v1.0
        with:
          repo-token: ${{ secrets.WORKFLOWSECRET || secrets.GITHUB_TOKEN}}
          repository: alwx/rasa
          directory: /
          package-manager: pip
          batch-size: 5
